# Generated by Django 3.1.6 on 2021-04-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20210402_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
